name: "🚀 publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github v2"
        uses: actions/checkout@v2

      - name: "Setup node env"
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      - name: build
        run: npm run build

      - name: minify
        run: npm run minify

      - name: pack
        run: npm pack --dry-run

      - name: publish
        run: npm publish
